default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: secret

development:
  <<: *default
  database: CashHoppersDB

test:
  <<: *default
  database: CashHoppersDB_test

production:
  <<: *default
  database: CashHoppersDB
